export const videoDisplayData = {
  text: "If you can't make it to church, don't worry! You can watch our services live every Sunday or catch up on previous sermons anytime. Stay connected to the word of God, no matter where you are.",
  heading: 'catch up on OUR previous sermons anytime',
  videoUrl: '/video/Video.mp4',
};

export const mediaCardData = [
  {
    id: '1',
    videoType: 'Youtube Video',
    creator: 'Prophet Adetola',
    videoUrl: '/video/Video.mp4',
    title: 'Ways to Live, Love, & Learn More about God',
  },
  {
    id: '2',
    videoType: 'Youtube Video',
    creator: 'Prophet Adetola',
    videoUrl: '/video/Video.mp4',
    title: 'Ways to Live, Love, & Learn More about God',
  },
  {
    id: '3',
    videoType: 'Youtube Video',
    creator: 'Prophet Adetola',
    videoUrl: '/video/Video.mp4',
    title: 'Ways to Live, Love, & Learn More about God',
  },
  {
    id: '4',
    videoType: 'Youtube Video',
    creator: 'Prophet Adetola',
    videoUrl: '/video/Video.mp4',
    title: 'Ways to Live, Love, & Learn More about God',
  },
  {
    id: '5',
    videoType: 'Youtube Video',
    creator: 'Prophet Adetola',
    videoUrl: '/video/Video.mp4',
    title: 'Ways to Live, Love, & Learn More about God',
  },
  {
    id: '6',
    videoType: 'Youtube Video',
    creator: 'Prophet Adetola',
    videoUrl: '/video/Video.mp4',
    title: 'Ways to Live, Love, & Learn More about God',
  },
  {
    id: '7',
    videoType: 'Youtube Video',
    creator: 'Prophet Adetola',
    videoUrl: '/video/Video.mp4',
    title: 'Ways to Live, Love, & Learn More about God',
  },
  {
    id: '8',
    videoType: 'Youtube Video',
    creator: 'Prophet Adetola',
    videoUrl: '/video/Video.mp4',
    title: 'Ways to Live, Love, & Learn More about God',
  },
  {
    id: '9',
    videoType: 'Youtube Video',
    creator: 'Prophet Adetola',
    videoUrl: '/video/Video.mp4',
    title: 'Ways to Live, Love, & Learn More about God',
  },
  {
    id: '10',
    videoType: 'Youtube Video',
    creator: 'Prophet Adetola',
    videoUrl: '/video/Video.mp4',
    title: 'Ways to Live, Love, & Learn More about God',
  },
  {
    id: '11',
    videoType: 'Youtube Video',
    creator: 'Prophet Adetola',
    videoUrl: '/video/Video.mp4',
    title: 'Ways to Live, Love, & Learn More about God',
  },
  {
    id: '12',
    videoType: 'Youtube Video',
    creator: 'Prophet Adetola',
    videoUrl: '/video/Video.mp4',
    title: 'Ways to Live, Love, & Learn More about God',
  },
];
